"""Property tests for domain.filters (spec 3 hard rules, spec 31 Eligibility).

Listings and FX rates are SYNTHETIC values generated by Hypothesis.
"""

from __future__ import annotations

import decimal
from datetime import UTC, date, datetime
from decimal import Decimal
from pathlib import Path

from hypothesis import given, settings
from hypothesis import strategies as st

from suv_deals.domain.enums import (
    Availability,
    BodyType,
    EligibilityState,
    OdometerClaim,
    PriceBasis,
    PriceType,
    Tristate,
)
from suv_deals.domain.filters import screen
from suv_deals.domain.listings import LocationInfo, NormalizedListing, PriceInfo, VehicleSpec
from suv_deals.domain.money import FxRate
from suv_deals.domain.profiles import BusinessConfig, load_business_config
from suv_deals.domain.taxonomy import default_taxonomy

CONFIG_DIR = Path(__file__).resolve().parents[2] / "config"
AS_OF = date(2026, 10, 6)
DEFAULT = load_business_config(CONFIG_DIR)
ALL_ENABLED = load_business_config(
    CONFIG_DIR,
    overrides={"profiles": {"manual_4000": {"enabled": True}, "below_target_watch": {"enabled": True}}},
)
ELIGIBLE = {EligibilityState.ELIGIBLE_PRIMARY, EligibilityState.ELIGIBLE_MANUAL_PROFILE}


def synthetic(
    price_minor: int, mileage_km: Decimal, currency: str = "EUR", country: str = "DE"
) -> NormalizedListing:
    return NormalizedListing(
        source_key="fixture_dealer_de",
        source_listing_id="SYNTH-PROP",
        canonical_url="https://dealer.example/vehicles/SYNTH-PROP",
        observed_at=datetime(2026, 10, 6, 10, 0, tzinfo=UTC),
        location=LocationInfo(country=country),
        availability=Availability.AVAILABLE,
        vehicle=VehicleSpec(
            make="Toyota",
            model="RAV4",
            body_type=BodyType.SUV,
            mileage_km=mileage_km,
            mileage_claim=OdometerClaim.SELLER_REPORTED,
        ),
        price=PriceInfo(
            amount_minor=price_minor,
            currency=currency,
            basis=PriceBasis.GROSS,
            type=PriceType.FULL_VEHICLE_ASKING,
            required_seller_fees_known=Tristate.NO,
        ),
        parser_version="fixture@1.0.0",
    )


def state_for(
    price_minor: int, config: BusinessConfig = DEFAULT, mileage: str = "150000"
) -> EligibilityState:
    return screen(synthetic(price_minor, Decimal(mileage)), config, [], AS_OF, default_taxonomy()).state


@settings(max_examples=150)
@given(prices=st.lists(st.integers(min_value=200_000, max_value=350_000), min_size=3, max_size=3))
def test_screening_is_monotone_in_price_within_band(prices: list[int]) -> None:
    low, mid, high = sorted(prices)
    if state_for(low) == state_for(high) == EligibilityState.ELIGIBLE_PRIMARY:
        assert state_for(mid) == EligibilityState.ELIGIBLE_PRIMARY


@settings(max_examples=150)
@given(price=st.integers(min_value=0, max_value=1_000_000))
def test_primary_band_is_exactly_2500_to_3000_inclusive(price: int) -> None:
    eligible = state_for(price) == EligibilityState.ELIGIBLE_PRIMARY
    assert eligible == (250_000 <= price <= 300_000)


@settings(max_examples=150)
@given(price=st.integers(min_value=300_001, max_value=2_000_000))
def test_above_3000_never_primary_even_with_all_profiles(price: int) -> None:
    assert state_for(price, ALL_ENABLED) != EligibilityState.ELIGIBLE_PRIMARY


@settings(max_examples=200)
@given(
    price=st.integers(min_value=0, max_value=500_000),
    mileage=st.decimals(min_value=Decimal("200000"), max_value=Decimal("2000000"), places=3, allow_nan=False),
)
def test_mileage_at_or_above_200000_never_eligible(price: int, mileage: Decimal) -> None:
    result = screen(synthetic(price, mileage), ALL_ENABLED, [], AS_OF, default_taxonomy())
    assert result.state not in ELIGIBLE


@settings(max_examples=150)
@given(
    mileage=st.decimals(min_value=Decimal("1"), max_value=Decimal("199999.999"), places=3, allow_nan=False)
)
def test_mileage_below_limit_does_not_block(mileage: Decimal) -> None:
    result = screen(synthetic(275_000, mileage), DEFAULT, [], AS_OF, default_taxonomy())
    assert result.state == EligibilityState.ELIGIBLE_PRIMARY


@settings(max_examples=150)
@given(
    chf_minor=st.integers(min_value=150_000, max_value=400_000),
    rate=st.decimals(min_value=Decimal("0.80"), max_value=Decimal("1.10"), places=4, allow_nan=False),
)
def test_chf_eligibility_matches_unrounded_division(chf_minor: int, rate: Decimal) -> None:
    fx = FxRate(
        base="EUR",
        quote="CHF",
        rate=rate,
        rate_date=AS_OF,
        retrieved_at=datetime(2026, 10, 6, 6, 0, tzinfo=UTC),
        provider="synthetic-test",
    )
    result = screen(
        synthetic(chf_minor, Decimal("150000"), "CHF", "CH"), DEFAULT, [fx], AS_OF, default_taxonomy()
    )
    eur = decimal.Context(prec=40).divide(Decimal(chf_minor) / 100, rate)
    assert result.eur_amount == eur
    expected = Decimal("2500") <= eur <= Decimal("3000")
    assert (result.state == EligibilityState.ELIGIBLE_PRIMARY) == expected
