"""Property tests for domain.parsing (spec 31: Locale parsing unit/property tests).

Inputs are SYNTHETIC values generated by Hypothesis.
"""

from __future__ import annotations

from datetime import UTC, date, datetime
from decimal import Decimal

from hypothesis import given, settings
from hypothesis import strategies as st

from suv_deals.domain.parsing import (
    MILES_TO_KM,
    parse_displacement,
    parse_first_registration,
    parse_mileage,
    parse_number,
    parse_power,
    parse_price,
    parse_source_datetime,
)

LOCALE_FORMATS: dict[str, tuple[tuple[str, ...], str]] = {
    # locale: (group separators that may be used, decimal mark)
    "de": ((".", "\u00a0", "\u202f", " ", "'"), ","),
    "it": ((".", "\u00a0", " "), ","),
    "mk": ((".", " ", "\u00a0"), ","),
    "ch": (("'", "\u2019", " ", "\u202f", "\u2009"), "."),
    "en": ((",", " "), "."),
}


def format_number(integer: int, cents: int | None, group: str, decimal_mark: str) -> str:
    digits = str(integer)
    groups: list[str] = []
    while len(digits) > 3:
        groups.insert(0, digits[-3:])
        digits = digits[:-3]
    groups.insert(0, digits)
    text = group.join(groups)
    if cents is not None:
        text += f"{decimal_mark}{cents:02d}"
    return text


@settings(max_examples=400)
@given(
    locale=st.sampled_from(sorted(LOCALE_FORMATS)),
    integer=st.integers(min_value=0, max_value=999_999_999),
    cents=st.one_of(st.none(), st.integers(min_value=0, max_value=99)),
    data=st.data(),
)
def test_formatted_numbers_round_trip(
    locale: str, integer: int, cents: int | None, data: st.DataObject
) -> None:
    groups, decimal_mark = LOCALE_FORMATS[locale]
    group = data.draw(st.sampled_from(groups))
    text = format_number(integer, cents, group, decimal_mark)
    expected = Decimal(integer) if cents is None else Decimal(f"{integer}.{cents:02d}")
    result = parse_number(text, locale)  # type: ignore[arg-type]
    assert result.value == expected, text
    assert not result.ambiguous


@given(
    head=st.integers(min_value=1, max_value=999),
    tail=st.integers(min_value=0, max_value=999),
    mark=st.sampled_from([",", "."]),
)
def test_lone_separator_with_three_digits_is_ambiguous_without_locale(
    head: int, tail: int, mark: str
) -> None:
    result = parse_number(f"{head}{mark}{tail:03d}", None)
    assert result.value is None
    assert result.ambiguous


@given(text=st.text(max_size=120))
def test_parsers_never_raise_and_never_go_negative(text: str) -> None:
    for locale in (None, "de", "ch", "en"):
        number = parse_number(text, locale)
        assert number.value is None or number.value >= 0
        price = parse_price(text, locale)
        assert price.amount is None or price.amount >= 0
        mileage = parse_mileage(text, locale)
        assert mileage.km is None or mileage.km > 0


@given(miles=st.integers(min_value=1, max_value=900_000))
def test_miles_conversion_is_exact_and_unrounded(miles: int) -> None:
    result = parse_mileage(f"{miles} mi", "de")
    assert result.km == Decimal(miles) * MILES_TO_KM
    assert result.original.amount == Decimal(miles)


@given(km=st.integers(min_value=1, max_value=1_999_999), group=st.sampled_from([".", " ", "\u00a0"]))
def test_de_mileage_round_trip(km: int, group: str) -> None:
    text = format_number(km, None, group, ",") + " km"
    assert parse_mileage(text, "de").km == Decimal(km)


AS_OF = datetime(2026, 10, 6, 10, 0, tzinfo=UTC)


@given(text=st.text(max_size=80))
def test_date_power_displacement_parsers_never_raise(text: str) -> None:
    registration = parse_first_registration(text, as_of=AS_OF.date())
    assert registration.value.value is None or registration.value.year is not None
    stamp = parse_source_datetime(text, "Europe/Berlin", AS_OF)
    assert stamp.timestamp.value is None or stamp.timestamp.value.tzinfo is not None
    power = parse_power(text)
    assert power.kw is None or 1 <= power.kw <= 2000
    displacement = parse_displacement(text)
    assert displacement.cm3 is None or 50 <= displacement.cm3 <= 10000


@given(moment=st.datetimes(min_value=datetime(1, 1, 2), max_value=datetime(9999, 12, 30)))
def test_iso_timestamps_with_offset_never_raise(moment: datetime) -> None:
    text = moment.replace(tzinfo=UTC).isoformat()
    result = parse_source_datetime(text, "Europe/Berlin", AS_OF)
    value = result.timestamp.value
    if value is not None:
        assert value == moment.replace(tzinfo=UTC)
        assert value <= AS_OF.replace(day=7)


@given(year=st.integers(min_value=1950, max_value=2026), month=st.integers(min_value=1, max_value=12))
def test_registration_month_round_trip(year: int, month: int) -> None:
    result = parse_first_registration(f"EZ {month:02d}/{year}", as_of=date(2026, 12, 31))
    assert result.value.value == f"{year:04d}-{month:02d}"
