"""Property tests for technical-inspection wording (domain.parsing.parse_inspection).

Inputs are SYNTHETIC values generated by Hypothesis. The binding property: negated, expired or
past-dated inspection wording is never a positive roadworthy claim, whatever text surrounds it,
and seller wording is never a verified inspection.
"""

from __future__ import annotations

from datetime import date

from hypothesis import given, settings
from hypothesis import strategies as st

from suv_deals.domain.enums import ClaimStatus
from suv_deals.domain.parsing import ParseWarning, parse_inspection

# Negated / not-fresh / expired seller wording (DE, CH, IT, Swiss French).
NEGATED_FORMS = (
    "vor MFK",
    "vor der MFK",
    "nicht ab MFK",
    "nicht frisch ab MFK",
    "nicht mehr ab MFK",
    "ohne MFK",
    "keine MFK",
    "muss zur MFK",
    "nicht vorgeführt",
    "MFK abgelaufen",
    "MFK fällig",
    "ohne TÜV",
    "kein TÜV",
    "keine HU",
    "ohne HU/AU",
    "ohne gültigen TÜV",
    "kein neuer TÜV",
    "TÜV abgelaufen",
    "HU abgelaufen",
    "TÜV fällig",
    "revisione scaduta",
    "scaduta la revisione",
    "senza revisione",
    "non revisionata",
    "non è ancora revisionata",
    "da revisionare",
    "revisione da fare",
    "senza collaudo",
    "da collaudare",
    "sans expertise",
    "sans l'expertise",
    "non expertisé",
    "non expertisée",
    "pas encore expertisée",
    "à expertiser",
    "expertise échue",
)
POSITIVE_FORMS = ("ab MFK", "frisch ab MFK", "MFK neu", "TÜV neu", "HU/AU neu", "revisionata", "expertisé")
FILLER_WORDS = (
    "Occasion",
    "Export",
    "ohne",
    "nicht",
    "frisch",
    "neu",
    "Service",
    "CHF 2'990.-",
    "inkl. MWST",
    "Export ohne MWST",
    "ab Platz",
    "auf Wunsch",
    "2025",
    "05/2027",
    "km",
    "Garantie",
    "revisione",
    "expertise",
    *POSITIVE_FORMS,
)
# A bare date right after "TÜV fällig"/"MFK fällig" turns it into a due-date statement ("TÜV fällig
# 05/2027" = due in May 2027), so the negation property uses date-free filler; dated wording has its
# own properties below.
NEGATION_FILLER = tuple(w for w in FILLER_WORDS if w not in {"2025", "05/2027"})
LOCALES = st.sampled_from(["de", "it", "ch", "mk", "en", None])
AS_OF = st.dates(min_value=date(2015, 1, 1), max_value=date(2040, 12, 31))


def _case(text: str, mode: int) -> str:
    return (text, text.upper(), text.lower(), text.title())[mode]


def _filler(words: list[str]) -> str:
    return " ".join(words)


@settings(max_examples=600)
@given(
    phrase=st.sampled_from(NEGATED_FORMS),
    case=st.integers(min_value=0, max_value=3),
    before=st.lists(st.sampled_from(NEGATION_FILLER), max_size=6),
    after=st.lists(st.sampled_from(NEGATION_FILLER), max_size=6),
    separator=st.sampled_from([" ", ", ", ". ", " \u00b7 ", "\n", " \u00a0"]),
    locale=LOCALES,
    as_of=AS_OF,
)
def test_negated_inspection_wording_is_never_positive(
    phrase: str,
    case: int,
    before: list[str],
    after: list[str],
    separator: str,
    locale: str | None,
    as_of: date,
) -> None:
    text = separator.join(p for p in (_filler(before), _case(phrase, case), _filler(after)) if p)
    result = parse_inspection(text, locale, as_of)  # type: ignore[arg-type]
    assert result.roadworthy_claim not in (ClaimStatus.SELLER_CLAIMED, ClaimStatus.VERIFIED), text
    assert result.fresh_inspection is False, text


@settings(max_examples=400)
@given(
    template=st.sampled_from(
        [
            "HU bis {mm}/{yyyy}",
            "TÜV {mm}/{yyyy}",
            "TÜV: {mm}.{yyyy}",
            "HU {mm}/{yy}",
            "HU/AU neu bis {mm}/{yyyy}",
            "MFK bis {mm}/{yyyy}",
            "nächste MFK {mm}/{yyyy}",
            "revisione fino a {mm}/{yyyy}",
            "scadenza revisione {mm}/{yyyy}",
            "prochaine expertise {mm}/{yyyy}",
        ]
    ),
    as_of=AS_OF,
    months_back=st.integers(min_value=1, max_value=12 * 20),
    before=st.lists(st.sampled_from(FILLER_WORDS), max_size=4),
)
def test_stated_past_expiry_is_never_positive(
    template: str, as_of: date, months_back: int, before: list[str]
) -> None:
    index = as_of.year * 12 + (as_of.month - 1) - months_back
    year, month = divmod(index, 12)
    month += 1
    text = template.format(mm=f"{month:02d}", yyyy=f"{year:04d}", yy=f"{year % 100:02d}")
    result = parse_inspection(f"{_filler(before)} {text}".strip(), "de", as_of)
    assert result.roadworthy_claim not in (ClaimStatus.SELLER_CLAIMED, ClaimStatus.VERIFIED), text
    assert result.fresh_inspection is False
    if result.inspection_expiry.value == f"{year:04d}-{month:02d}":
        assert ParseWarning.INSPECTION_EXPIRED in result.warnings


@settings(max_examples=300)
@given(
    template=st.sampled_from(["HU bis {mm}/{yyyy}", "MFK bis {mm}/{yyyy}", "revisione fino a {mm}/{yyyy}"]),
    as_of=AS_OF,
    months_ahead=st.integers(min_value=0, max_value=12 * 4),
)
def test_stated_future_expiry_is_kept_exactly(template: str, as_of: date, months_ahead: int) -> None:
    index = as_of.year * 12 + (as_of.month - 1) + months_ahead
    year, month = divmod(index, 12)
    month += 1
    result = parse_inspection(template.format(mm=f"{month:02d}", yyyy=f"{year:04d}"), "ch", as_of)
    assert result.inspection_expiry.value == f"{year:04d}-{month:02d}"
    assert result.roadworthy_claim == ClaimStatus.SELLER_CLAIMED
    assert ParseWarning.INSPECTION_EXPIRED not in result.warnings


@settings(max_examples=500)
@given(text=st.text(max_size=300), locale=LOCALES, as_of=AS_OF)
def test_arbitrary_text_never_crashes_and_is_never_verified(
    text: str, locale: str | None, as_of: date
) -> None:
    result = parse_inspection(text, locale, as_of)  # type: ignore[arg-type]
    assert result.roadworthy_claim != ClaimStatus.VERIFIED
    assert not result.fresh_inspection or result.roadworthy_claim == ClaimStatus.SELLER_CLAIMED
    expiry = result.inspection_expiry
    if expiry.year is not None:
        assert as_of.year - 30 <= expiry.year <= as_of.year + 5
    last = result.last_inspection
    if last.year is not None:
        assert last.year <= as_of.year


@settings(max_examples=200)
@given(
    words=st.lists(
        st.sampled_from(
            [*FILLER_WORDS, "HU", "TÜV", "MFK", "bis", "fino", "a", "letzte", "vor", "\u00a0", "13/2027"]
        ),
        max_size=12,
    ),
    as_of=AS_OF,
)
def test_word_soup_respects_the_model_invariants(words: list[str], as_of: date) -> None:
    result = parse_inspection(" ".join(words), "ch", as_of)
    assert result.roadworthy_claim != ClaimStatus.VERIFIED
    if result.fresh_inspection:
        assert result.roadworthy_claim == ClaimStatus.SELLER_CLAIMED
