import { expect, test } from '@playwright/test'
import { expectNoHorizontalScroll, expectNoXss, guard, manifest, signIn } from './helpers.ts'

test.describe('read-only screens', () => {
  test('overview shows sources, scans, coverage gaps, reviews, deliveries and blockers', async ({ page }) => {
    const { problems } = guard(page)
    await signIn(page, 'reviewer')
    await expect(page.getByText(/source is paused: no new network work runs/)).toBeVisible()
    await expect(page.locator('.stat').filter({ hasText: 'Running sources' })).toContainText('1')
    await expect(page.locator('.stat').filter({ hasText: 'Last successful scan' }).locator('time')).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Coverage gaps' })).toBeVisible()
    await expect(page.getByText('budget limited', { exact: false }).first()).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Activation blockers' })).toBeVisible()
    const deliveries = page.locator('#overview-outbox')
    await expect(deliveries.getByText('dead letter')).toBeVisible()
    await expect(deliveries.getByText('uncertain').first()).toBeVisible()
    expect(problems).toEqual([])
  })

  test('candidate queue filters, detail and back/forward navigation keep their state', async ({ page }) => {
    const data = manifest()
    const { problems } = guard(page)
    await signIn(page, 'reviewer')
    await page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'Candidates' }).click()
    const table = page.getByRole('table', { name: 'Candidates' })
    await expect(table.getByText(data.titles.alpha)).toBeVisible()
    await expect(table.getByText(data.titles.net_only)).toBeVisible()
    // Price in the original currency, EUR equivalent, km and country are shown per row.
    const alphaRow = table.locator('tr', { hasText: data.titles.alpha })
    await expect(alphaRow).toContainText('EUR 2,750.00')
    await expect(alphaRow).toContainText('187,500 km')
    await expect(alphaRow).toContainText('DE')
    await expect(alphaRow).toContainText('eligible primary')
    const netRow = table.locator('tr', { hasText: data.titles.net_only })
    await expect(netRow).toContainText('needs facts')
    await expect(netRow.locator('td[data-label="EUR equivalent"]')).toContainText('unknown')

    await page.getByLabel('Status').selectOption('rejected')
    await page.getByRole('button', { name: 'Apply filters' }).click()
    await expect(page).toHaveURL(/\/candidates\?status=rejected$/)
    await expect(table.getByText(data.titles.rejected)).toBeVisible()
    await expect(table.getByText(data.titles.alpha)).toHaveCount(0)
    await expect(table.locator('tr', { hasText: data.titles.rejected })).toContainText('200,000 km')

    await table.locator('tr', { hasText: data.titles.rejected }).getByRole('link').click()
    await expect(page).toHaveURL(new RegExp(`/candidates/${data.listings.rejected}$`))
    await expect(page.getByText('MILEAGE_TOO_HIGH')).toBeVisible()

    await page.goBack()
    await expect(page).toHaveURL(/\/candidates\?status=rejected$/)
    await expect(page.getByLabel('Status')).toHaveValue('rejected')
    await expect(table.getByText(data.titles.rejected)).toBeVisible()
    await page.goForward()
    await expect(page).toHaveURL(new RegExp(`/candidates/${data.listings.rejected}$`))
    await page.goBack()
    await page.goBack()
    await expect(page).toHaveURL(/\/candidates$/)
    await expect(page.getByLabel('Status')).toHaveValue('')
    expect(problems).toEqual([])
  })

  test('candidate detail: safe source link, provenance as extraction confidence, history, checklist', async ({ page }) => {
    const data = manifest()
    await signIn(page, 'reviewer')
    await page.goto(`/candidates/${data.listings.alpha}`)
    const source = page.getByRole('link', { name: /Open the source listing/ })
    await expect(source).toHaveAttribute('target', '_blank')
    await expect(source).toHaveAttribute('rel', 'noopener noreferrer')
    await expect(source).toHaveAttribute('href', /^https:\/\/synthetic-dealer\.example\//)
    await expect(page.getByText('extraction confidence, not truth')).toBeVisible()
    await expect(page.locator('#price').getByText('decrease')).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Due-diligence checklist' })).toBeVisible()
    await expect(page.locator('#lifecycle')).toContainText('First seen by this system')
    await expect(page.locator('#provenance')).toContainText('vehicle.mileage_km')
    // The credential-bearing provenance URL was dropped by the backend: no link is rendered for it.
    await expect(page.locator('#provenance a[href*="@"]')).toHaveCount(0)
  })

  test('economics shows unknown costs as "unknown", never EUR 0.00, with the PROPOSED threshold', async ({ page }) => {
    const data = manifest()
    const { problems } = guard(page)
    await signIn(page, 'reviewer')
    await page.goto(`/candidates/${data.listings.alpha}`)
    await page.getByRole('link', { name: 'Economics' }).click()
    await expect(page.getByRole('heading', { name: 'Economics', level: 1 })).toBeVisible()
    const costs = page.getByRole('table', { name: 'Cost lines' })
    const transport = costs.locator('tr', { hasText: 'SYNTHETIC transport (no quote yet)' })
    await expect(transport.locator('td[data-label="Base"]')).toHaveText('unknown')
    await expect(transport.locator('td[data-label="Status"]')).toContainText('unknown')
    await expect(costs.locator('tr', { hasText: 'SYNTHETIC repairs estimate' }).locator('td[data-label="Base"]')).toHaveText('EUR 800.00')
    await expect(page.getByTestId('threshold')).toContainText('PROPOSED')
    await expect(page.getByText(/Conservative estimated contribution before business tax/)).toBeVisible()
    await expect(page.getByText('Known subtotal (not a total)').first()).toBeVisible()
    await expect(page.locator('#tax')).toContainText('unknown')
    const amounts = await page.locator('.amount').allTextContents()
    expect(amounts.length).toBeGreaterThan(5)
    for (const amount of amounts) expect(amount).not.toMatch(/(^|\s)0(\.00)?$/)
    await expect(page.getByRole('heading', { name: 'Asking prices (advertised, not sales)' })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Seller-reported sales (unverified)' })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Verified sales' })).toBeVisible()
    await expect(page.locator('#versions')).toContainText('Calculation version')
    expect(problems).toEqual([])
  })

  test('malicious seller text renders inert in the queue, detail and review screens', async ({ page }) => {
    const data = manifest()
    const { problems } = guard(page)
    await signIn(page, 'reviewer')
    await page.goto('/candidates')
    await expect(page.getByRole('table', { name: 'Candidates' }).getByText(data.titles.xss)).toBeVisible()
    await expectNoXss(page)
    await page.goto(`/candidates/${data.listings.xss}`)
    await expect(page.getByText(data.titles.xss).first()).toBeVisible()
    await expect(page.getByText(/<script>window\.xssProbe=2<\/script>/)).toBeVisible()
    await expect(page.getByText('<svg onload="window.xssProbe=4">SYNTHETIC turbo noise</svg>')).toBeVisible()
    await expect(page.getByText('<iframe src="javascript:window.xssProbe=5"></iframe>')).toBeVisible()
    await expectNoXss(page)
    await page.goto(`/reviews/${data.cases.xss}`)
    await expect(page.getByText(data.titles.xss).first()).toBeVisible()
    await expectNoXss(page)
    await page.goto('/reviews')
    await expect(page.getByText(data.titles.xss)).toBeVisible()
    await expectNoXss(page)
    expect(problems).toEqual([])
  })

  test('a viewer sees no mutation controls', async ({ page }) => {
    const data = manifest()
    await signIn(page, 'viewer')
    await page.goto(`/reviews/${data.cases.delta}`)
    await expect(page.getByText(/Read-only: your role \(viewer\)/)).toBeVisible()
    await expect(page.getByRole('button', { name: /Claim/ })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Submit decision' })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Needs inspection' })).toHaveCount(0)
    await page.goto(`/candidates/${data.listings.alpha}`)
    await expect(page.getByRole('heading', { name: 'Private notes' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Add note' })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Request recheck' })).toHaveCount(0)
    await page.goto('/sources')
    await expect(page.getByRole('heading', { name: 'Technical status (separate from terms)' }).first()).toBeVisible()
    await expect(page.getByRole('button', { name: 'Pause this source' })).toHaveCount(0)
    await page.goto('/settings')
    await expect(page.getByTestId('profile-manual_4000')).toContainText('DISABLED')
    await expect(page.getByTestId('owner-admin')).toHaveCount(0)
  })

  test('settings: disabled EUR 4,000 profile, PROPOSED threshold, owner-only administration', async ({ page }) => {
    await signIn(page, 'owner')
    await page.goto('/settings')
    const manual = page.getByTestId('profile-manual_4000')
    await expect(manual).toContainText('DISABLED - optional manual-review profile')
    await expect(page.getByTestId('settings-threshold')).toContainText('EUR 1,500.00')
    await expect(page.getByTestId('settings-threshold')).toContainText('PROPOSED')
    await expect(page.getByTestId('owner-admin')).toBeVisible()
    await expect(page.locator('#bindings')).toContainText('SYNTHETIC private Slack channel')
  })

  test('sources: terms vs technical status, rate budget, run history, and an owner pause with a reason', async ({ page }) => {
    const { problems } = guard(page)
    await signIn(page, 'owner')
    await page.goto('/sources')
    const never = page.locator('section', { hasText: 'SYNTHETIC never source' })
    await expect(never.getByRole('heading', { name: 'Terms (audit record)' })).toBeVisible()
    await expect(never.getByRole('heading', { name: 'Technical status (separate from terms)' })).toBeVisible()
    await expect(page.locator('section', { hasText: 'SYNTHETIC running source' }).getByRole('heading', { name: 'Recent runs' })).toBeVisible()
    await expect(page.locator('section', { hasText: 'SYNTHETIC paused source' })).toContainText('SYNTHETIC owner pause for maintenance')
    const pause = never.getByRole('button', { name: 'Pause this source' })
    await expect(pause).toBeDisabled()
    await never.getByLabel(/Pause reason/).fill('SYNTHETIC E2E pause: parser drift suspected')
    const response = page.waitForResponse((r) => r.url().includes('/pause') && r.request().method() === 'POST')
    await pause.click()
    expect((await response).status()).toBe(200)
    // After the reload shows the source as paused, the server confirmation is still on screen.
    await expect(never.getByText(/No new network work runs for this source/)).toBeVisible()
    await expect(never.getByText(/Resuming is not available from the dashboard/)).toBeVisible()
    await expect(never.getByText('Source paused.')).toBeVisible()
    await expect(never.getByRole('button', { name: 'Pause this source' })).toHaveCount(0)
    expect(problems).toEqual([])
  })
})

test.describe('phone-sized viewport', () => {
  test.use({ viewport: { width: 375, height: 812 }, isMobile: true, hasTouch: true })

  test('navigation works through the menu and nothing scrolls horizontally', async ({ page }) => {
    const data = manifest()
    const { problems } = guard(page)
    await signIn(page, 'reviewer')
    await expectNoHorizontalScroll(page)
    const nav = page.getByRole('navigation', { name: 'Primary' })
    await expect(nav).toBeHidden()
    const menu = page.getByRole('button', { name: 'Menu' })
    await expect(menu).toHaveAttribute('aria-expanded', 'false')
    await menu.click()
    await expect(nav).toBeVisible()
    await nav.getByRole('link', { name: 'Candidates' }).click()
    await expect(page.getByRole('heading', { name: 'Candidate queue' })).toBeVisible()
    await expect(nav).toBeHidden()
    await expectNoHorizontalScroll(page)
    await page.goto(`/candidates/${data.listings.alpha}`)
    await expect(page.getByRole('heading', { name: 'Normalized specification' })).toBeVisible()
    await expectNoHorizontalScroll(page)
    await page.goto(`/candidates/${data.listings.xss}`)
    await expect(page.getByRole('heading', { name: 'Seller text (untrusted)' })).toBeVisible()
    await expectNoHorizontalScroll(page)
    await page.goto(`/candidates/${data.listings.alpha}/economics`)
    await expect(page.getByRole('heading', { name: 'Cost lines' })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Versions and dependencies' })).toBeVisible()
    await expectNoHorizontalScroll(page)
    await page.goto('/reviews')
    await expect(page.getByRole('heading', { name: 'Review queue' })).toBeVisible()
    await expectNoHorizontalScroll(page)
    await page.goto(`/reviews/${data.cases.delta}`)
    await expect(page.getByRole('heading', { name: 'Decision history' })).toBeVisible()
    await expectNoHorizontalScroll(page)
    await page.goto('/settings')
    await expect(page.getByRole('heading', { name: 'Activation gates' })).toBeVisible()
    await expectNoHorizontalScroll(page)
    await page.getByRole('button', { name: 'Menu' }).click()
    await nav.getByRole('link', { name: 'Sources' }).click()
    await expect(page.getByRole('heading', { name: 'Sources', level: 1 })).toBeVisible()
    await expectNoHorizontalScroll(page)
    expect(problems).toEqual([])
  })

  test('keyboard: skip link and visible focus', async ({ page }) => {
    await signIn(page, 'reviewer')
    await page.keyboard.press('Tab')
    const skip = page.getByRole('link', { name: 'Skip to content' })
    await expect(skip).toBeFocused()
    const outline = await skip.evaluate((element) => getComputedStyle(element).outlineStyle)
    expect(outline).not.toBe('none')
  })
})
