"""RFC 5322 / MIME builder for the bounded seller inquiry (spec 37.1, 37.3, 37.5).

One message shape only: a single ``text/plain; charset="utf-8"`` part (quoted-printable or
base64 body), built with Python's ``email`` package (``EmailMessage`` + ``policy.SMTP``), with
exactly these headers and nothing else::

    From: <verified display name> <verified sender address>
    To: <exactly one verified seller address>          (no display name: seller text never
                                                        enters a header)
    Reply-To: <verified alias>                          (optional)
    Subject: <rendered template subject>               (RFC 2047 encoded when non-ASCII)
    Date: <RFC 5322 date, UTC>
    Message-ID: <inquiry-<uuid>.<attempt>@<sender-domain>>
    X-SUV-Inquiry-Ref: inquiry-<uuid>                  (the inquiry id only; never a secret)
    MIME-Version: 1.0
    Content-Type: text/plain; charset="utf-8"
    Content-Transfer-Encoding: quoted-printable | base64

There is no Cc, Bcc, Resent-*, In-Reply-To/References (an initial inquiry is never a reply or a
follow-up), no multipart container and no attachment: the API offers no way to add them, and
``verify_built_message`` re-parses the final bytes and refuses anything else.

Header-injection defence (defence in depth, all mandatory):

1. Every header input is NFC-normalised and rejected when it contains CR, LF, NUL, any other
   control character, U+0085/U+2028/U+2029 line separators, Unicode format characters (bidi
   overrides, zero-width), surrogates, private-use or unassigned code points, RFC 2047
   encoded-word markers (``=?``/``?=``) or exceeds its length bound.
2. Addresses use a conservative RFC 5321/5322 subset (``seller_contacts.canonicalize_address``):
   dot-atom local part of common characters only (no quoted strings, comments, group syntax,
   route addresses, ``%`` source-route hacks or SMTPUTF8 local parts), IDNA-encoded lower-case
   domain, total <= 254. Commas, semicolons, angle brackets or whitespace (a second recipient)
   are rejected.
3. Display names reject RFC 5322 specials (``<>@,;:"\\[]()``) so an attacker-shaped name can
   never smuggle an address, and are RFC 2047 encoded by the library when non-ASCII.
4. The generated bytes are parsed again and checked: header allow-list with exact counts,
   CRLF-only line endings, physical lines <= 998 octets, folded continuation lines, exactly one
   To mailbox (no groups), no defects, single non-multipart ``text/plain`` UTF-8 part, and the
   decoded subject/body/addresses equal the inputs exactly (an encoded-word smuggled into the
   subject would decode differently and is refused).

Bounded scope: ``build_inquiry_message`` accepts only the exact deterministic rendering of a
registered seller template (``seller_templates.rendering_problems``) whose scope validates with the
real transport envelope, and stores that rendering on the ``BuiltMessage``. ``inquiry_scope_problems``
re-checks it, and every provider runs it before any I/O: a message assembled any other way (for
example with ``build_message`` from free text) is never transmitted.

Determinism: the same ``OutboundInquiryMessage`` always yields the same bytes (explicit
``Date``, no random MIME boundary because there is a single part, fixed header order), so
``raw_sha256`` identifies the exact transmitted request. A Python upgrade could in principle
change header folding; the hash is therefore recorded per attempt, never recomputed later.

Message-ID: ``<inquiry-<inquiry uuid>.<attempt number>@<sender domain>>``, stable for one
attempt (rebuilding the same attempt yields the same Message-ID and bytes) and different for
each new attempt so reconciliation evidence is attributable to an attempt. Reusing a Message-ID
is NOT a universal server-side de-duplication guarantee: providers may rewrite it (Gmail and
Exchange may assign their own), may accept the same Message-ID twice, and Outlook ``.Send`` may
ignore a client value. The value is a correlation and search key only; an uncertain send is
never retried on the assumption that a provider will drop the duplicate.
"""

from __future__ import annotations

import base64
import hashlib
import re
import unicodedata
from datetime import datetime
from email import policy
from email.headerregistry import Address
from email.message import EmailMessage
from email.parser import BytesParser
from email.utils import format_datetime
from typing import Any, Final, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from suv_deals.clock import ensure_utc
from suv_deals.domain.seller_contacts import AddressError, canonicalize_address
from suv_deals.domain.seller_templates import (
    MessageEnvelope,
    RenderedMessage,
    message_body_hash,
    rendering_problems,
    validate_scope,
)
from suv_deals.errors import ValidationFailed

MIME_BUILDER_VERSION: Final = "mime-builder/1"
MAX_DISPLAY_NAME_CHARS: Final = 64
MAX_SUBJECT_CHARS: Final = 200
MAX_BODY_CHARS: Final = 4_000
MAX_ADDRESS_CHARS: Final = 254
MAX_MESSAGE_BYTES: Final = 64 * 1024
MAX_HEADER_LINE_OCTETS: Final = 998  # RFC 5322 section 2.1.1 hard limit (excluding CRLF)
FOLD_LINE_LENGTH: Final = 78  # RFC 5322 recommended limit used for folding
MAX_ATTEMPT_NUMBER: Final = 99
INQUIRY_REF_HEADER: Final = "X-SUV-Inquiry-Ref"
CONTENT_TYPE_VALUE: Final = 'text/plain; charset="utf-8"'

TransferEncoding = Literal["quoted-printable", "base64"]

_FROZEN = ConfigDict(frozen=True, extra="forbid")
_POLICY: Final = policy.SMTP.clone(max_line_length=FOLD_LINE_LENGTH)
_PARSE_POLICY: Final = policy.default

#: Header name -> (required, maximum count). Nothing outside this map may appear.
_HEADER_RULES: Final[dict[str, tuple[bool, int]]] = {
    "from": (True, 1),
    "to": (True, 1),
    "reply-to": (False, 1),
    "subject": (True, 1),
    "date": (True, 1),
    "message-id": (True, 1),
    INQUIRY_REF_HEADER.lower(): (True, 1),
    "mime-version": (True, 1),
    "content-type": (True, 1),
    "content-transfer-encoding": (True, 1),
}
_HEADER_ORDER: Final = (
    "From",
    "To",
    "Reply-To",
    "Subject",
    "Date",
    "Message-ID",
    INQUIRY_REF_HEADER,
    "MIME-Version",
    "Content-Type",
    "Content-Transfer-Encoding",
)
#: Characters that are never acceptable in any header input (checked before normalisation too).
_LINE_BREAKS: Final = frozenset("\r\n\x00\x0b\x0c\x1c\x1d\x1e\x85\u2028\u2029")
_FORBIDDEN_CATEGORIES: Final = frozenset({"Cc", "Cf", "Co", "Cs", "Cn", "Zl", "Zp"})
_DISPLAY_SPECIALS: Final = frozenset('<>@,;:"\\[]()')
_UUID_TEXT: Final = r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
_MESSAGE_ID_RE: Final = re.compile(
    rf"^<inquiry-(?P<uuid>{_UUID_TEXT})\.(?P<attempt>[1-9][0-9]?)@(?P<domain>[a-z0-9.-]{{1,253}})>$"
)
_INQUIRY_REF_RE: Final = re.compile(rf"^inquiry-(?P<uuid>{_UUID_TEXT})$")
_DOMAIN_LABEL_RE: Final = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")


class MimeBuildError(ValidationFailed):
    """The message (or one of its inputs) is refused; ``problems`` are stable codes."""

    def __init__(self, message: str, problems: list[str] | tuple[str, ...]) -> None:
        self.problems: tuple[str, ...] = tuple(sorted(set(problems)))
        super().__init__(message, details={"problems": list(self.problems)})


# =============================================================================================
# Input validation helpers
# =============================================================================================


def header_text_problems(value: str, *, max_chars: int, allow_empty: bool = False) -> list[str]:
    """Problems of an unstructured header input (subject or display name); codes only."""
    if not isinstance(value, str):
        return ["HEADER_VALUE_INVALID"]
    problems: list[str] = []
    if any(c in _LINE_BREAKS for c in value):
        problems.append("HEADER_INJECTION")
    normalized = unicodedata.normalize("NFC", value)
    if any(unicodedata.category(c) in _FORBIDDEN_CATEGORIES for c in normalized):
        problems.append("CONTROL_CHARACTER")
    if "=?" in normalized or "?=" in normalized:
        problems.append("ENCODED_WORD_NOT_ALLOWED")
    if not normalized.strip() and not allow_empty:
        problems.append("HEADER_VALUE_EMPTY")
    if normalized != normalized.strip() or "  " in normalized:
        problems.append("HEADER_WHITESPACE")
    if len(normalized) > max_chars:
        problems.append("HEADER_VALUE_TOO_LONG")
    return problems


def display_name_problems(value: str) -> list[str]:
    problems = header_text_problems(value, max_chars=MAX_DISPLAY_NAME_CHARS)
    if any(c in _DISPLAY_SPECIALS for c in value):
        problems.append("DISPLAY_NAME_SPECIALS")
    return problems


def body_text_problems(value: str) -> list[str]:
    """The body may contain LF line breaks only; every other control/separator is refused."""
    if not isinstance(value, str):
        return ["BODY_INVALID"]
    problems: list[str] = []
    if "\r" in value or "\x85" in value or "\u2028" in value or "\u2029" in value:
        problems.append("BODY_LINE_BREAK_INVALID")
    normalized = unicodedata.normalize("NFC", value)
    if any(c != "\n" and unicodedata.category(c) in _FORBIDDEN_CATEGORIES for c in normalized):
        problems.append("CONTROL_CHARACTER")
    if not normalized.strip():
        problems.append("BODY_EMPTY")
    if len(normalized) > MAX_BODY_CHARS:
        problems.append("BODY_TOO_LONG")
    return problems


def _address_problems(raw: str) -> tuple[str | None, list[str]]:
    """Canonical address or problem codes (stricter than ``canonicalize_address`` alone)."""
    if not isinstance(raw, str):
        return None, ["ADDRESS_INVALID"]
    if any(c in _LINE_BREAKS for c in raw):
        return None, ["HEADER_INJECTION"]
    if len(raw) > MAX_ADDRESS_CHARS:
        return None, ["ADDRESS_TOO_LONG"]
    if raw != raw.strip() or any(c.isspace() for c in raw):
        return None, ["ADDRESS_INVALID"]
    if any(c in raw for c in ',;<>"()[]\\:%!'):  # second mailbox, route/% hack, group, quoting
        return None, ["ADDRESS_INVALID"]
    if any(unicodedata.category(c) in _FORBIDDEN_CATEGORIES for c in raw):
        return None, ["CONTROL_CHARACTER"]
    if raw.count("@") != 1 or not raw.split("@", 1)[0].isascii():
        return None, ["ADDRESS_INVALID"]  # no SMTPUTF8 local parts
    try:
        canonical = canonicalize_address(raw).canonical
    except AddressError as exc:
        code = "HEADER_INJECTION" if exc.problem == "HEADER_INJECTION" else "ADDRESS_INVALID"
        return None, [code]
    if len(canonical) > MAX_ADDRESS_CHARS:
        return None, ["ADDRESS_TOO_LONG"]
    return canonical, []


class MailboxAddress(BaseModel):
    """A validated mailbox: canonical address (IDNA domain) and an optional safe display name."""

    model_config = _FROZEN

    address: str = Field(max_length=MAX_ADDRESS_CHARS)
    display_name: str | None = Field(default=None, max_length=MAX_DISPLAY_NAME_CHARS)

    @field_validator("address")
    @classmethod
    def _address(cls, value: str) -> str:
        canonical, problems = _address_problems(value)
        if problems or canonical is None:
            raise ValueError("address rejected: " + ", ".join(problems))
        if canonical != value:
            raise ValueError("address must already be canonical; use mailbox()")
        return value

    @field_validator("display_name")
    @classmethod
    def _display(cls, value: str | None) -> str | None:
        if value is None:
            return None
        problems = display_name_problems(value)
        if problems:
            raise ValueError("display name rejected: " + ", ".join(sorted(set(problems))))
        if unicodedata.normalize("NFC", value) != value:
            raise ValueError("display name must be NFC; use mailbox()")
        return value

    @property
    def local_part(self) -> str:
        return self.address.split("@", 1)[0]

    @property
    def domain(self) -> str:
        return self.address.split("@", 1)[1]

    def header_address(self) -> Address:
        return Address(display_name=self.display_name or "", username=self.local_part, domain=self.domain)


def mailbox(address: str, display_name: str | None = None) -> MailboxAddress:
    """Validate and canonicalise; raises ``MimeBuildError`` with problem codes."""
    canonical, problems = _address_problems(address)
    name: str | None = None
    if display_name is not None:
        problems.extend(display_name_problems(display_name))
        name = unicodedata.normalize("NFC", display_name)
    if problems or canonical is None:
        raise MimeBuildError("mailbox rejected", problems)
    return MailboxAddress(address=canonical, display_name=name)


# =============================================================================================
# Message-ID and inquiry reference
# =============================================================================================


class InquiryMessageRef(BaseModel):
    model_config = _FROZEN

    inquiry_id: UUID
    attempt_number: int = Field(ge=1, le=MAX_ATTEMPT_NUMBER)
    domain: str


def _valid_domain(domain: str) -> bool:
    labels = domain.split(".")
    return (
        0 < len(domain) <= 253
        and len(labels) >= 2
        and all(_DOMAIN_LABEL_RE.fullmatch(label) for label in labels)
    )


def inquiry_message_id(inquiry_id: UUID, attempt_number: int, sender_domain: str) -> str:
    """``<inquiry-<uuid>.<attempt>@<sender-domain>>`` (see module docstring for semantics)."""
    if not isinstance(attempt_number, int) or not 1 <= attempt_number <= MAX_ATTEMPT_NUMBER:
        raise MimeBuildError("attempt number out of range", ["ATTEMPT_NUMBER_INVALID"])
    if not _valid_domain(sender_domain):
        raise MimeBuildError("sender domain invalid", ["SENDER_DOMAIN_INVALID"])
    return f"<inquiry-{inquiry_id}.{attempt_number}@{sender_domain}>"


def parse_inquiry_message_id(value: str | None) -> InquiryMessageRef | None:
    """Parse a Message-ID generated by this module; anything else (or a variant) is ``None``."""
    if not isinstance(value, str):
        return None
    match = _MESSAGE_ID_RE.fullmatch(value.strip())
    if match is None or not _valid_domain(match.group("domain")):
        return None
    return InquiryMessageRef(
        inquiry_id=UUID(match.group("uuid")),
        attempt_number=int(match.group("attempt")),
        domain=match.group("domain"),
    )


def inquiry_ref_value(inquiry_id: UUID) -> str:
    """Value of ``X-SUV-Inquiry-Ref``: the inquiry id only (no secret, no personal data)."""
    return f"inquiry-{inquiry_id}"


def parse_inquiry_ref(value: str | None) -> UUID | None:
    if not isinstance(value, str):
        return None
    match = _INQUIRY_REF_RE.fullmatch(value.strip())
    return UUID(match.group("uuid")) if match else None


# =============================================================================================
# Specification and result
# =============================================================================================


class OutboundInquiryMessage(BaseModel):
    """Everything that goes into the message. There are deliberately no cc/bcc/attachment fields."""

    model_config = _FROZEN

    inquiry_id: UUID
    attempt_number: int = Field(ge=1, le=MAX_ATTEMPT_NUMBER)
    sender: MailboxAddress
    recipient: MailboxAddress
    reply_to: MailboxAddress | None = None
    subject: str = Field(max_length=MAX_SUBJECT_CHARS * 2)
    body: str = Field(max_length=MAX_BODY_CHARS * 2)
    date: datetime
    transfer_encoding: TransferEncoding = "quoted-printable"

    @field_validator("date")
    @classmethod
    def _date(cls, value: datetime) -> datetime:
        return ensure_utc(value).replace(microsecond=0)

    @model_validator(mode="after")
    def _roles(self) -> OutboundInquiryMessage:
        if not self.sender.display_name:
            raise ValueError("the verified sender display name is required")
        if self.recipient.display_name is not None:
            raise ValueError("the recipient carries no display name (seller text never enters headers)")
        if self.reply_to is not None and self.reply_to.display_name is not None:
            raise ValueError("Reply-To carries no display name")
        if self.recipient.address.casefold() == self.sender.address.casefold():
            raise ValueError("recipient must not be the sender")
        if (
            self.reply_to is not None
            and self.reply_to.address.casefold() == self.recipient.address.casefold()
        ):
            raise ValueError("Reply-To must be the sender's verified alias, never the recipient")
        return self


class BuiltMessage(BaseModel):
    """The exact bytes to submit plus the metadata the attempt record stores."""

    model_config = _FROZEN

    builder_version: str = MIME_BUILDER_VERSION
    inquiry_id: UUID
    attempt_number: int = Field(ge=1, le=MAX_ATTEMPT_NUMBER)
    rfc_message_id: str
    inquiry_ref: str
    from_address: str
    from_display_name: str
    to_address: str
    reply_to_address: str | None
    subject: str
    body: str
    date: datetime
    transfer_encoding: TransferEncoding
    body_hash: str
    raw: bytes = Field(max_length=MAX_MESSAGE_BYTES)
    raw_sha256: str
    size_bytes: int = Field(ge=1, le=MAX_MESSAGE_BYTES)
    #: The exact registered-template rendering this message was built from (set only by
    #: ``build_inquiry_message``). ``None`` means "not a seller inquiry": providers refuse it.
    rendered: RenderedMessage | None = None

    @model_validator(mode="after")
    def _consistent(self) -> BuiltMessage:
        if hashlib.sha256(self.raw).hexdigest() != self.raw_sha256 or len(self.raw) != self.size_bytes:
            raise ValueError("raw bytes do not match their hash/size")
        if self.rendered is not None and (
            self.rendered.kind != "seller_inquiry"
            or self.rendered.body_hash != self.body_hash
            or self.rendered.placeholders.sender_display_name != self.from_display_name
        ):
            raise ValueError("the rendered template does not match the built message")
        if parse_inquiry_message_id(self.rfc_message_id) != InquiryMessageRef(
            inquiry_id=self.inquiry_id,
            attempt_number=self.attempt_number,
            domain=self.from_address.split("@", 1)[-1],
        ):
            raise ValueError("Message-ID does not match inquiry, attempt and sender domain")
        if self.inquiry_ref != inquiry_ref_value(self.inquiry_id):
            raise ValueError("inquiry reference does not match the inquiry id")
        if self.body_hash != message_body_hash(self.subject, self.body):
            raise ValueError("body hash does not match subject and body")
        return self

    @property
    def sender_domain(self) -> str:
        return self.from_address.split("@", 1)[1]

    def raw_base64url(self) -> str:
        """URL-safe base64 of the RFC 2822 bytes (Gmail ``users.messages.send`` ``raw``)."""
        return base64.urlsafe_b64encode(self.raw).decode("ascii")

    def raw_base64(self) -> str:
        """Standard base64 of the MIME bytes (Microsoft Graph ``sendMail`` MIME body)."""
        return base64.b64encode(self.raw).decode("ascii")

    def header_values(self) -> dict[str, str]:
        """The structured header values as serialised (unfolded), for scope validation/audit."""
        parsed = BytesParser(policy=_PARSE_POLICY).parsebytes(self.raw)
        return {
            name: " ".join(str(parsed[name]).split()) for name in _HEADER_ORDER if parsed[name] is not None
        }

    def envelope(self) -> MessageEnvelope:
        """Transport envelope for ``seller_templates.validate_scope``: every extra header of the
        final bytes, including the technical ``X-SUV-Inquiry-Ref`` correlation header (allow-listed
        by ``seller_templates`` with the exact value shape ``inquiry-<lower-case uuid>``)."""
        values = self.header_values()
        extra = {
            name: values[name]
            for name in (
                "Message-ID",
                "Date",
                INQUIRY_REF_HEADER,
                "MIME-Version",
                "Content-Type",
                "Content-Transfer-Encoding",
            )
        }
        return MessageEnvelope(
            to=(self.to_address,),
            reply_to=(self.reply_to_address,) if self.reply_to_address else (),
            extra_headers=extra,
        )


# =============================================================================================
# Building
# =============================================================================================


def _wire_body(body: str) -> str:
    return body if body.endswith("\n") else body + "\n"


def build_message(spec: OutboundInquiryMessage) -> BuiltMessage:
    """Build and verify the RFC 5322 bytes; raises ``MimeBuildError`` with problem codes.

    The result carries no template rendering, so no provider will transmit it: seller inquiries
    are built with ``build_inquiry_message``.
    """
    return _build(spec, rendered=None)


def _build(spec: OutboundInquiryMessage, *, rendered: RenderedMessage | None) -> BuiltMessage:
    subject = unicodedata.normalize("NFC", spec.subject)
    body = unicodedata.normalize("NFC", spec.body)
    problems = header_text_problems(spec.subject, max_chars=MAX_SUBJECT_CHARS)
    problems.extend(body_text_problems(spec.body))
    if problems:
        raise MimeBuildError("message content rejected", problems)

    message_id = inquiry_message_id(spec.inquiry_id, spec.attempt_number, spec.sender.domain)
    ref = inquiry_ref_value(spec.inquiry_id)
    msg = EmailMessage(policy=_POLICY)
    try:
        msg["From"] = spec.sender.header_address()
        msg["To"] = spec.recipient.header_address()
        if spec.reply_to is not None:
            msg["Reply-To"] = spec.reply_to.header_address()
        msg["Subject"] = subject
        msg["Date"] = format_datetime(spec.date)
        msg["Message-ID"] = message_id
        msg[INQUIRY_REF_HEADER] = ref
        msg["MIME-Version"] = "1.0"
        msg.set_content(_wire_body(body), subtype="plain", charset="utf-8", cte=spec.transfer_encoding)
        raw = msg.as_bytes(policy=_POLICY)
    except (ValueError, TypeError, UnicodeError) as exc:  # library-level refusal (defence in depth)
        raise MimeBuildError("message could not be serialised safely", ["SERIALISATION_REFUSED"]) from exc
    if len(raw) > MAX_MESSAGE_BYTES:
        raise MimeBuildError("message too large", ["MESSAGE_TOO_LARGE"])
    try:
        built = BuiltMessage(
            inquiry_id=spec.inquiry_id,
            attempt_number=spec.attempt_number,
            rfc_message_id=message_id,
            inquiry_ref=ref,
            from_address=spec.sender.address,
            from_display_name=spec.sender.display_name or "",
            to_address=spec.recipient.address,
            reply_to_address=spec.reply_to.address if spec.reply_to else None,
            subject=subject,
            body=body,
            date=spec.date,
            transfer_encoding=spec.transfer_encoding,
            body_hash=message_body_hash(subject, body),
            raw=raw,
            raw_sha256=hashlib.sha256(raw).hexdigest(),
            size_bytes=len(raw),
            rendered=rendered,
        )
    except ValueError as exc:  # pydantic ValidationError: the rendering does not match the message
        raise MimeBuildError("built message is inconsistent", ["BUILT_MESSAGE_INCONSISTENT"]) from exc
    verify_built_message(built)
    return built


def build_inquiry_message(
    rendered: RenderedMessage,
    *,
    inquiry_id: UUID,
    attempt_number: int,
    sender: MailboxAddress,
    recipient_address: str,
    reply_to_address: str | None,
    date: datetime,
    transfer_encoding: TransferEncoding = "quoted-printable",
) -> BuiltMessage:
    """Build the seller inquiry from a rendered, scope-validated template.

    Refused unless the rendered message is a seller inquiry (never the informational Macedonian
    preview) that is the exact deterministic rendering of a registered template
    (``seller_templates.rendering_problems``: a hand-built or edited message is never sent, even
    when its wording stays inside the scope), the From display name is exactly the signature's
    verified sender display name, and ``seller_templates.validate_scope`` passes for the message
    *with* the real transport envelope (one recipient, no Cc/Bcc, no attachment, allowed headers
    only).
    """
    problems: list[str] = []
    if rendered.kind != "seller_inquiry":
        problems.append("NOT_A_SELLER_MESSAGE")
    else:
        problems.extend(rendering_problems(rendered))
        problems.extend(validate_scope(rendered).problems)  # the precise scope codes, if any
    if sender.display_name != rendered.placeholders.sender_display_name:
        problems.append("SENDER_DISPLAY_NAME_MISMATCH")
    if problems:
        raise MimeBuildError("rendered message cannot be sent", problems)
    spec = OutboundInquiryMessage(
        inquiry_id=inquiry_id,
        attempt_number=attempt_number,
        sender=sender,
        recipient=mailbox(recipient_address),
        reply_to=mailbox(reply_to_address) if reply_to_address is not None else None,
        subject=rendered.subject,
        body=rendered.body,
        date=date,
        transfer_encoding=transfer_encoding,
    )
    if message_body_hash(spec.subject, spec.body) != rendered.body_hash:
        raise MimeBuildError("built message differs from the rendered template", ["BODY_HASH_MISMATCH"])
    built = _build(spec, rendered=rendered)
    problems = list(inquiry_scope_problems(built))
    if problems:
        raise MimeBuildError("message is outside the bounded inquiry scope", problems)
    return built


def inquiry_scope_problems(message: BuiltMessage) -> tuple[str, ...]:
    """Why ``message`` is not a sendable bounded seller inquiry (empty = it is).

    Requires the exact registered-template rendering the message was built from, that rendering
    still being exact (``rendering_problems``), byte-for-byte the same subject/body, and
    ``validate_scope`` passing with the message's real transport envelope. Every provider calls
    this (plus ``built_message_problems``) before any I/O, so free-text or edited messages,
    previews, extra recipients, Cc/Bcc or attachments never reach a provider.
    """
    rendered = message.rendered
    if rendered is None:
        return ("NOT_A_TEMPLATE_INQUIRY",)
    problems: list[str] = []
    if rendered.kind != "seller_inquiry":
        problems.append("NOT_A_SELLER_MESSAGE")
    problems.extend(rendering_problems(rendered))
    if rendered.body_hash != message.body_hash or rendered.body_hash != message_body_hash(
        message.subject, message.body
    ):
        problems.append("BODY_HASH_MISMATCH")
    if rendered.placeholders.sender_display_name != message.from_display_name:
        problems.append("SENDER_DISPLAY_NAME_MISMATCH")
    try:
        envelope = message.envelope()
    except (KeyError, ValueError):  # tampered bytes without one of the required headers
        return tuple(sorted({*problems, "ENVELOPE_INVALID"}))
    problems.extend(validate_scope(rendered, envelope=envelope).problems)
    return tuple(sorted(set(problems)))


# =============================================================================================
# Verification of final bytes (also used by every provider immediately before submission)
# =============================================================================================


def _raw_header_block_problems(raw: bytes) -> list[str]:
    problems: list[str] = []
    head, sep, _rest = raw.partition(b"\r\n\r\n")
    if not sep:
        return ["HEADER_BLOCK_UNTERMINATED"]
    if b"\x00" in raw:
        problems.append("NUL_BYTE")
    lines = raw.split(b"\r\n")
    if any(b"\r" in line or b"\n" in line for line in lines):
        problems.append("BARE_LINE_BREAK")
    if any(len(line) > MAX_HEADER_LINE_OCTETS for line in lines):
        problems.append("LINE_TOO_LONG")
    if any(byte > 0x7F for byte in head):
        problems.append("HEADER_NOT_ASCII")
    counts: dict[str, int] = {}
    for line in head.split(b"\r\n"):
        if line[:1] in (b" ", b"\t"):
            continue  # folded continuation
        name, colon, _value = line.partition(b":")
        if not colon or not name or name != name.strip():
            problems.append("HEADER_LINE_INVALID")
            continue
        key = name.decode("ascii", "replace").lower()
        counts[key] = counts.get(key, 0) + 1
    for key, count in counts.items():
        rule = _HEADER_RULES.get(key)
        if rule is None:
            problems.append(f"HEADER_NOT_ALLOWED:{key[:40]}")
        elif count > rule[1]:
            problems.append(f"HEADER_DUPLICATED:{key}")
    for key, (required, _max) in _HEADER_RULES.items():
        if required and key not in counts:
            problems.append(f"HEADER_MISSING:{key}")
    return problems


def _single_address(parsed: EmailMessage, name: str) -> str | None:
    header = parsed[name]
    if header is None:
        return None
    groups: tuple[Any, ...] = tuple(getattr(header, "groups", ()))
    addresses: tuple[Any, ...] = tuple(getattr(header, "addresses", ()))
    if len(groups) != 1 or groups[0].display_name is not None or len(addresses) != 1:
        return None
    return str(addresses[0].addr_spec)


def built_message_problems(message: BuiltMessage) -> tuple[str, ...]:
    """Every reason the final bytes are not exactly the allowed single-recipient text message."""
    raw = message.raw
    problems = _raw_header_block_problems(raw)
    if len(raw) > MAX_MESSAGE_BYTES:
        problems.append("MESSAGE_TOO_LARGE")
    if hashlib.sha256(raw).hexdigest() != message.raw_sha256:
        problems.append("RAW_HASH_MISMATCH")
    parsed = BytesParser(policy=_PARSE_POLICY).parsebytes(raw)
    if not isinstance(parsed, EmailMessage):  # pragma: no cover - policy.default guarantees it
        return (*problems, "PARSE_FAILED")
    if parsed.defects:
        problems.append("MESSAGE_DEFECTS")
    for name in ("cc", "bcc", "resent-to", "resent-cc", "resent-bcc", "in-reply-to", "references"):
        if parsed[name] is not None:
            problems.append("FORBIDDEN_HEADER")
    if parsed.is_multipart() or parsed.get_content_type() != "text/plain":
        problems.append("NOT_SINGLE_TEXT_PART")
    if (parsed.get_content_charset() or "").lower() != "utf-8":
        problems.append("CHARSET_NOT_UTF8")
    if parsed.get_content_disposition() is not None or parsed.get_filename() is not None:
        problems.append("ATTACHMENT")
    if str(parsed.get("Content-Transfer-Encoding", "")).strip().lower() != message.transfer_encoding:
        problems.append("TRANSFER_ENCODING_MISMATCH")
    if str(parsed.get("MIME-Version", "")).strip() != "1.0":
        problems.append("MIME_VERSION_INVALID")
    to_address = _single_address(parsed, "To")
    if to_address is None:
        problems.append("RECIPIENT_COUNT")
    elif to_address != message.to_address:
        problems.append("RECIPIENT_MISMATCH")
    from_header = parsed["From"]
    from_address = _single_address(parsed, "From")
    if from_address != message.from_address:
        problems.append("SENDER_MISMATCH")
    elif from_header is not None and from_header.addresses[0].display_name != message.from_display_name:
        problems.append("SENDER_DISPLAY_NAME_MISMATCH")
    if message.reply_to_address is None:
        if parsed["Reply-To"] is not None:
            problems.append("REPLY_TO_UNEXPECTED")
    elif _single_address(parsed, "Reply-To") != message.reply_to_address:
        problems.append("REPLY_TO_MISMATCH")
    if str(parsed.get("Message-ID", "")).strip() != message.rfc_message_id:
        problems.append("MESSAGE_ID_MISMATCH")
    if parse_inquiry_ref(str(parsed.get(INQUIRY_REF_HEADER, ""))) != message.inquiry_id:
        problems.append("INQUIRY_REF_MISMATCH")
    if str(parsed.get("Subject", "")) != message.subject:
        problems.append("SUBJECT_MISMATCH")  # also catches smuggled encoded-words
    date_header = parsed["Date"]
    if date_header is None or getattr(date_header, "datetime", None) != message.date:
        problems.append("DATE_MISMATCH")
    if not problems:
        try:
            content = parsed.get_content()
        except (LookupError, ValueError, UnicodeError):
            content = None
        if not isinstance(content, str) or content.replace("\r\n", "\n") != _wire_body(message.body):
            problems.append("BODY_MISMATCH")
    return tuple(sorted(set(problems)))


def verify_built_message(message: BuiltMessage) -> None:
    """Raise ``MimeBuildError`` unless the bytes are exactly the allowed message shape."""
    problems = built_message_problems(message)
    if problems:
        raise MimeBuildError("built message failed verification", problems)


__all__ = [
    "CONTENT_TYPE_VALUE",
    "INQUIRY_REF_HEADER",
    "MAX_ATTEMPT_NUMBER",
    "MAX_BODY_CHARS",
    "MAX_DISPLAY_NAME_CHARS",
    "MAX_HEADER_LINE_OCTETS",
    "MAX_MESSAGE_BYTES",
    "MAX_SUBJECT_CHARS",
    "MIME_BUILDER_VERSION",
    "BuiltMessage",
    "InquiryMessageRef",
    "MailboxAddress",
    "MimeBuildError",
    "OutboundInquiryMessage",
    "TransferEncoding",
    "body_text_problems",
    "build_inquiry_message",
    "build_message",
    "built_message_problems",
    "display_name_problems",
    "header_text_problems",
    "inquiry_message_id",
    "inquiry_ref_value",
    "inquiry_scope_problems",
    "mailbox",
    "parse_inquiry_message_id",
    "parse_inquiry_ref",
    "verify_built_message",
]
